# Python script containing 10 lines of code that include a print statement.
print("My first assignment in Python!")
print("I am excited to learn Python!")
print("I'm a Data Engineering intern at Ramana.")
print("I'm hoping this internship will help me learn more about Data.")
print("I'm also hoping to learn more about Python. Which is why I joined Elewa's Python Bootcamp")
print("I'm also hoping to learn more about SQL.")
print("This is about to be a fun journey!")
print("Most, actually all of these lines are just me rambling. lol")
print("Btw my internship is Learn on the Job. It has been one crazy ride fr!!!")
print("I'm done now. Bye!")